import type { EditablePageSlug } from "./pageOverrides";

export type EditablePageDefinition = {
  slug: EditablePageSlug;
  title: string;
  routePath: string;
  textKeys: string[];
};

export const EDITABLE_PAGES: EditablePageDefinition[] = [
  {
    slug: "about",
    title: "Om-siden",
    routePath: "/om",
    textKeys: [
      "about.hero.title",
      "about.hero.tagline",
      "about.started.title",
      "about.started.p1",
      "about.started.p2",
      "about.workshop.title",
      "about.workshop.p1",
      "about.workshop.p2",
      "about.quality.title",
      "about.quality.p1",
      "about.quality.p2",
      "about.principles.title",
      "about.principles.lead",
      "about.principles.bullets.singleSource",
      "about.principles.bullets.singleSourceBody",
      "about.principles.bullets.predictability",
      "about.principles.bullets.predictabilityBody",
      "about.principles.bullets.respect",
      "about.principles.bullets.respectBody",
      "about.principles.bullets.realWork",
      "about.principles.bullets.realWorkBody",
      "about.principles.outro",
      "about.principles.outroEm",
      "about.deliver.title",
      "about.deliver.p1",
      "about.deliver.linkLead",
      "about.deliver.linkCta",
      "about.direction.title",
      "about.direction.p1",
      "about.direction.linkLead",
      "about.direction.linkCta",
    ],
  },
  {
    slug: "services",
    title: "Tjenester / Idébank",
    routePath: "/idebank",
    textKeys: [
      "services.hero.title",
      "services.hero.tagline",
      "services.hero.p1",
      "services.hero.p2",
      "services.hero.back",
      "services.hero.contact",
      "services.model1.label",
      "services.model1.title",
      "services.model1.lead",
      "services.model1.bullets.b1Strong",
      "services.model1.bullets.b1",
      "services.model1.bullets.b2Strong",
      "services.model1.bullets.b2",
      "services.model1.bullets.b3Strong",
      "services.model1.bullets.b3",
      "services.model1.p1",
      "services.model1.cta",
      "services.model2.label",
      "services.model2.title",
      "services.model2.lead",
      "services.model2.bullets.b1Strong",
      "services.model2.bullets.b1",
      "services.model2.bullets.b2Strong",
      "services.model2.bullets.b2",
      "services.model2.bullets.b3Strong",
      "services.model2.bullets.b3",
      "services.model2.p1a",
      "services.model2.p1bStrong",
      "services.model2.p1c",
      "services.model2.submitEmailCta",
      "services.interesting.title",
      "services.interesting.lead",
      "services.interesting.bullets.b1",
      "services.interesting.bullets.b2",
      "services.interesting.bullets.b3",
      "services.interesting.bullets.b4",
      "services.interesting.exampleLead",
      "services.interesting.exampleCta",
    ],
  },
];
